T2:snappi_tests:400g support for snappi_tests/pfcwd/test_pfcwd_actions.py and snappi_tests/pfc/test_pfc_no_congestion_throughput.py
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit easier:
-->
### Description of PR
<!--
- Please include a summary of the change and which issue is fixed.
- Please also include relevant motivation and context. Where should reviewer start? background context?
- List any dependencies that are required for this change.
-->

Summary:
Adding support for 400G runs in these scripts. The changes include:
1. Adding 400G to the no_congenstion_throughput script's options.
2. Reducing the code footprint in pfcwd_actions script.
3. Fixturize the cleanup part of the testcases in pfcwd_actions.
4. Adding multi-udp stream for cisco-8000 in pfcwd_actions helper.
5. Updated the skip messages for the testcases to clarify why it is skipped.

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [X] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [X] 202405
- [X] 202411
- [X] 202505

### Approach
#### What is the motivation for this PR?
Need support for cisco-8000 for 400G in these new scripts.

#### How did you do it?
Pls see description.

#### How did you verify/test it?
Ran the scripts to success:
test_pfcwd_actions.py:
```
=========================================================================================================================== PASSES ===========================================================================================================================
_______________________________________________________________________________________________ test_pfcwd_drop_90_10[multidut_port_info0-verify_port_speed1] ________________________________________________________________________________________________
_______________________________________________________________________________________________ test_pfcwd_drop_90_10[multidut_port_info1-verify_port_speed1] ________________________________________________________________________________________________
________________________________________________________________________________________________ test_pfcwd_drop_uni[multidut_port_info0-verify_port_speed1] _________________________________________________________________________________________________
________________________________________________________________________________________________ test_pfcwd_drop_uni[multidut_port_info1-verify_port_speed1] _________________________________________________________________________________________________
___________________________________________________________________________________ test_pfcwd_drop_over_subs_40_09[multidut_port_info0-verify_port_speed_oversubscribe1] ____________________________________________________________________________________
___________________________________________________________________________________ test_pfcwd_drop_over_subs_40_09[multidut_port_info1-verify_port_speed_oversubscribe1] ____________________________________________________________________________________
____________________________________________________________________________________ test_pfcwd_disable_pause_cngtn[multidut_port_info0-verify_port_speed_oversubscribe1] ____________________________________________________________________________________
____________________________________________________________________________________ test_pfcwd_disable_pause_cngtn[multidut_port_info1-verify_port_speed_oversubscribe1] ____________________________________________________________________________________
------------------------------------------------------------------------------- generated xml file: /run_logs/ixia/full-actions/2025-07-22-20-43-24/tr_2025-07-22-20-43-24.xml -------------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
================================================================================================================== short test summary info ===================================================================================================================
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_90_10[multidut_port_info0-verify_port_speed1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_90_10[multidut_port_info1-verify_port_speed1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_uni[multidut_port_info0-verify_port_speed1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_uni[multidut_port_info1-verify_port_speed1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_over_subs_40_09[multidut_port_info0-verify_port_speed_oversubscribe1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_drop_over_subs_40_09[multidut_port_info1-verify_port_speed_oversubscribe1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info0-verify_port_speed_oversubscribe1]
PASSED snappi_tests/pfcwd/test_pfcwd_actions.py::test_pfcwd_disable_pause_cngtn[multidut_port_info1-verify_port_speed_oversubscribe1]
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:86: Need Minimum of 2 ports of speed 100G defined in ansible/files/*links.csv file
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:212: Need Minimum of 2 ports of speed 100G defined in ansible/files/*links.csv file
SKIPPED [4] snappi_tests/pfcwd/test_pfcwd_actions.py:339: Forward action is not supported in cisco-8000.
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:506: Need Minimum of 3 ports of speed 100G defined in ansible/files/*links.csv file
SKIPPED [4] snappi_tests/pfcwd/test_pfcwd_actions.py:641: Forward action is not supported in cisco-8000.
SKIPPED [2] snappi_tests/pfcwd/test_pfcwd_actions.py:808: Need Minimum of 3 ports of speed 100G defined in ansible/files/*links.csv file
=================================================================================================== 8 passed, 16 skipped, 9 warnings in 8888.34s (2:28:08) ===================================================================================================
sonic@snappi-sonic-mgmt-msft-t2-400g-WB:/data/tests$
```

test_pfc_no_congestion_throughput.py:
```
=========================================================================================================================== PASSES ===========================================================================================================================
________________________________________________________________________________________________ test_multiple_prio_diff_dist[multidut_port_info1-port_map1] _________________________________________________________________________________________________
_________________________________________________________________________________________________ test_multiple_prio_uni_dist[multidut_port_info0-port_map1] _________________________________________________________________________________________________
_________________________________________________________________________________________________ test_multiple_prio_uni_dist[multidut_port_info1-port_map1] _________________________________________________________________________________________________
__________________________________________________________________________________________________ test_single_lossless_prio[multidut_port_info0-port_map1] __________________________________________________________________________________________________
__________________________________________________________________________________________________ test_single_lossless_prio[multidut_port_info1-port_map1] __________________________________________________________________________________________________
------------------------------------------------------------------------- generated xml file: /run_logs/ixia/no_congestion_throughput/2025-07-18-15-18-40/tr_2025-07-18-15-18-40.xml -------------------------------------------------------------------------
INFO:root:Can not get Allure report URL. Please check logs
================================================================================================================== short test summary info ===================================================================================================================
PASSED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_multiple_prio_diff_dist[multidut_port_info1-port_map1]
PASSED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_multiple_prio_uni_dist[multidut_port_info0-port_map1]
PASSED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_multiple_prio_uni_dist[multidut_port_info1-port_map1]
PASSED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_single_lossless_prio[multidut_port_info0-port_map1]
PASSED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_single_lossless_prio[multidut_port_info1-port_map1]
SKIPPED [6] common/helpers/assertions.py:16: Need Minimum of 2 ports defined in ansible/files/*links.csv file
FAILED snappi_tests/pfc/test_pfc_no_congestion_throughput.py::test_multiple_prio_diff_dist[multidut_port_info0-port_map1] - Failed: Loss seen on TGEN
============================================================================================== 1 failed, 5 passed, 6 skipped, 7 warnings in 5363.63s (1:29:23) ===========================================
```
The failure above is due to another issue from CRC errors in the wire. Its not related to the script.
#### Any platform specific information?
Specifig to cisco-8000 only.