argparse conflicting option string
### Description of PR
Two option strings, `--num_routes` and `--skip_cleanup` conflict between a couple of test suites.  This causes `./run_tests.sh` when executing test cases simultaneously (such as when running the full suite) to exit with an error of something like:
```
argparse.ArgumentError: argument --num_routes: conflicting option string(s): --num_routes
```

Move these arguments into the global scope from their conflicting locations.

Fixes https://github.com/sonic-net/sonic-mgmt/issues/5526

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

### Back port request
- [ ] 202012
- [ ] 202205
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411

### Approach
#### What is the motivation for this PR?

Make running all tests pass

#### How did you do it?

Move conflicting options to global scope.

#### How did you verify/test it?
```
./run_tests.sh -n vms-kvm-t0 -d vlab-01 -f vtestbed.yaml -i ../ansible/veos_vtb -e "--neighbor_type=sonic" -t t0,any
```

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->