Bug ID: 19675: Bug:Test tests/smartswitch/platform_tests/test_platform_dpu.py::test_data_control_mid_plane_sync causes issues with CHASSIS_STATE_DB
**Description of the bug**

The CHASSIS_DBs are bound to the IP address of the bridge-midplane interface, so during the execution of the test test_data_control_mid_plane_sync the [bridge-midplane is set to down](https://github.com/sonic-net/sonic-mgmt/blob/5cd4e4092cf22bff5ae3176c269b8c53383ad3e7/tests/smartswitch/platform_tests/test_platform_dpu.py#L339) causing the CHASSIS_DBs to go down, causing traceback error in show system-health dpu output :

Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/show/system_health.py", line 248, in dpu
    show_dpu_state(module_name)
  File "/usr/local/lib/python3.11/dist-packages/show/system_health.py", line 174, in show_dpu_state
    chassis_state_db.connect(chassis_state_db.CHASSIS_STATE_DB)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 2059, in connect
    return _swsscommon.SonicV2Connector_Native_connect(self, db_name, retry_on)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to connect to redis - Connection timed out(1): Cannot assign requested address
This should ideally be in a fixture, so that on test failure we set the interface back to up, as the ip link command executed is not reset even on config reload

**Steps to Reproduce**

On a mellanox smart-switch:
sudo ip link set bridge-midplane down
Check the system-health output:
show system-health dpu DPU0

**Actual Behavior and Expected Behavior**

**Actual Behaviour:**
Traceback and test failure, interface is set to down even after test has finished on failure
Expected behaviour:
No traceback, test should not introduce changes which would cause issues later since the interface is set to down.

We can use the dpu interfaces to set the midplane to down instead of the bridge-midplane interface itself

Which release branch to backport
[x] 202505
[x] 202506